### ISSUE TITLE
.CTR models are messed up

### ISSUE THREAD

**Issue by R7CrazyCanucks** [CTR-tools/CTR-tools#16]
Hello. I tried converting a .ctr model from the game and the model is messed up. Example: model_reader.exe Crash.ctr. And i view it in meshlab and it's messed up. could this be fixed?

**Comment by DCxDemo** [comment]
It's not possible, because animated model format is unknown.

**Comment by DCxDemo** [comment]
closing this as #58 is used to track the issue.
