### ISSUE TITLE
[lev] Fix incorrect 8 bit textures export

### ISSUE THREAD

**Issue by SlavaVlasov** [CTR-tools/CTR-tools#17]
http://prntscr.com/u9vw82

"Race today" incorrectly displayed, is it possible to fix it?

**Comment by DCxDemo** [comment]
some progress, expecting to be fixed soon

![unknown](https://user-images.githubusercontent.com/13422696/141698368-9e225cbb-a19f-4b90-93e4-d1ef70e1a52b.png)

**Comment by DCxDemo** [comment]
Fixed.

![](https://cdn.discordapp.com/attachments/527136512882769930/909888977740374016/0005_151121_093304.jpg)
