### ISSUE TITLE
[Viewer] Mistaken level in Adventure Hubs

### ISSUE THREAD

**Issue by nonunknown** [CTR-tools/CTR-tools#61]
![Screenshot_1](https://user-images.githubusercontent.com/58845030/109499631-eb279680-7a73-11eb-948f-cf8e1624ab01.png)

As you can see, `ALL AT ONCE` takes the user to Dingo's Canyone instead of showing all adventure hub levels!

**Comment by DCxDemo** [comment]
Fixed in https://github.com/CTR-tools/CTR-tools/commit/6b8e245ea75c1fed0d0707efe0e1fcf53b1763a6
