### ISSUE TITLE
[general] Update .NET target version

### ISSUE THREAD

**Issue by TheBetaM** [CTR-tools/CTR-tools#77]
The .NET Framework 4.5 SDK is no longer available to download and the runtime will be unavailable soon aswell: https://docs.microsoft.com/en-us/lifecycle/announcements/sha-1-signed-content-retired

This makes it unable to build as intended.

**Comment by DCxDemo** [comment]
Updated to 4.6, which gives at least one more year, eventually will have to migrate framework to .net standard, but that'll require more changes.

**Comment by DCxDemo** [comment]
Updated to 4.6.2 https://github.com/CTR-tools/CTR-tools/commit/d6013b0a186a250373f96da38e5b17e3a1b1fd9d

**Comment by DCxDemo** [comment]
Moving to https://github.com/CTR-tools/CTR-tools/issues/128
