### ISSUE TITLE
Cant pack new textures to VRAM

### ISSUE THREAD

**Issue by YAGAMI55** [CTR-tools/CTR-tools#84]
So. I extract all texture from data.vram via ctr-tools-gui in vram section
then i have folders like texMed/low/hi/models with textures .png inside each folder. Ok. It good
But i cant pack modified textures

new data.vram is same original
then i look via Tile Molester at new data.vram - nothing has change. textures inside as original

maybe need more detailed instructions in read.me?

**Comment by DCxDemo** [comment]
check vram_packer readme in r11

**Comment by YAGAMI55** [comment]
> check vram_packer readme in r11
> https://github.com/DCxDemo/CTR-tools/releases/download/r11prev/vram_packer.zip

Hmmm.... I’ll do that. But not results. Maybe because texture is a Model Texture?
